---
language: python

python: 3.7
dist: xenial

env:
  global:
    - TL_VERSION=2019
    - PATH=$HOME/texlive/$TL_VERSION/bin/x86_64-linux:$PATH

install:
  - pip install https://github.com/MaxNoe/texlive-batch-installation/archive/master.tar.gz
  - |
    python -m install_texlive -p $HOME/texlive -t 2019 --collections='-acfghuDFG' \
    -i 'koma-script,polyglossia,csquotes,placeins,enumitem,biber,biblatex,ncctools,filehook,xpatch,logreq,xstring,siunitx,pdftexcmds,kvoptions,stringenc'

script:
  latexmk
